# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

# Perform the action when we manually create a release through Github UI
# Code > Releases > Manually add an increment number
# If current is 0.0.1, then add 0.0.2 and press enter
# on:
#   release:
#     types: [created]
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'SKIP SCRIPTS')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: cd libs/antd-v5 && yarn && cd .. && cd .. && yarn && yarn build
      - name: publish-antd
        if: "contains(github.event.head_commit.message, 'publish-antd')"
        run: cd dist/libs/antd && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish-utils
        if: "contains(github.event.head_commit.message, 'publish-utils')"
        run: cd dist/libs/utils && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish-antd-v5
        if: "contains(github.event.head_commit.message, 'publish-antd-v5')"
        run: cd dist/libs/antd-v5 && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
